import { useRouter } from 'next/router'
import Head from 'next/head'


// export async function getStaticProps(){
//     try {
//       let request = await fetch(`https://pokeapi.co/api/v2/pokemon/${id}`);
//       console.log(request);
//       return request.json(); 
//     } catch (error) {
//       console.log(error);
//     }
// }

// export async function getStaticPaths() {
    
// }

export default function Poke() {
    
    const router = useRouter()
    const { id } = router.query
    console.log(id);
  
  return (
    <>
        <Head>
        <title>Pokedex | Mofe620</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <p>Pokeman: {id}</p>
    </>
  );
}

//This page loads localhost:3000/id
//As opposed to the other one which loads localhost:3000/pokemon?id
// Learn how to use both
//Dynamic Paths like this [id].js require getStaticProps and getStaticPaths
