import Head from 'next/head'
import Link from 'next/link'

export default function Home({newPokemonArray}) {

  const pokedex = newPokemonArray;



  return (
    <>
      <Head>
        <title>Pokedex | Mofe620</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-200 w-full h-full p-2 md:p-20">
        <h2 className='text-slate-700 text-2xl font-semibold  text-center'>Pokedexxx</h2>
        <div className="bg-white text-slate-500 rounded-md mx-auto md:w-2/5 w-4/5 mt-2 h-3/4 p-1 md:p-4">
          <p className='text-center'>Click a name to view the Pokeman in it's full glory</p>
          <div className="">
            {pokedex.map((pokeman, index) => (
              <div className='flex justify-between px-8 mt-4 '>
                <Link href={`/pokeman?id=${index + 1}`}>
                  <a className='text-lg text-slate-500 font-mono hover:border-solid hover:border-2 border-none hover:border-b-blue-400'>{index+1}. {pokeman.name}</a>
                </Link>
                <img src={pokeman.image} alt="pokeman" width="50px"  />
              </div>
            ))}
          </div>
        </div>
      </div> 
    </>
  )
}

export async function getStaticProps(){
  try {
    let request = await fetch('https://pokeapi.co/api/v2/pokemon?limit=70');
    let response = await request.json();

    const pokemonArray = response.results;

    //add imageUrl property
    const newPokemonArray = pokemonArray.map((pokemon, index) => {
      //we can't pass in indices of 1, 2, 3 because the url is formatted in 3 digits, so we can fix that
      const paddedId = ('00' + (index + 1));
      //ensure the id we're passing is not more than 3 digits. 
      //For instance, '00' + 34 = 0034 which is not valid so we strip the last 3 digits in any circumstance. 
      //Even 00150 will then be stripped to 150
      const imageId = paddedId.slice(-3);
      //the following url will provide the image for each image index but it doesn't come with the fetch result
      const image = `https://assets.pokemon.com/assets/cms2/img/pokedex/detail/${imageId}.png`;
      return {...pokemon, image}
    })

    return {
      props: { newPokemonArray }
    };
    
  } catch (error) {
    console.log(error);
  }
  
}
